name: metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["stable", "main"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: Carnagion
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Europe/Berlin
          config_output: commit
          committer_branch: metrics
          committer_message: Update metrics
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 9
          plugin_habits_languages_threshold: 0%
          plugin_music: yes
          plugin_music_token: "0332bb39bdbb45abb3f8f34a5db96ed7, 9371aff26e8e41579d4a37632f368f0e, AQDHBxkaAjBXtXJd_nwJVisZ5iDuW4fNDvZauyP5K1ol9Pz2avV7Cydv7cJs-MUPvp3iHDtvZGuVL9JXexJmVe5XD-_VXkiASckeNpDDVvRwsRbKQOksInE1nPeLxp3B_ro"
          plugin_music_limit: 3
          plugin_music_mode: top
          plugin_music_played_at: yes
          plugin_music_provider: spotify
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_user: Carnagion
